// RUNLU Warehouse AI V6.12.0 Build086 — RUNLU Live Links Pilot
(() => {
  if (window.__RUNLU_BUILD086__) return;
  window.__RUNLU_BUILD086__ = true;

  const PAGE='liveLowStockPage';
  let installed=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function ready(){return typeof window.showPage==='function'&&typeof window.loadMasters==='function'&&typeof window.loadInventoryRecords==='function'&&typeof window.carpetRecords==='function'}
  function ensureStyle(){if(document.getElementById('build086LiveLinksStyle'))return;const s=document.createElement('style');s.id='build086LiveLinksStyle';s.textContent=`
    .dashboardMetric.live086{cursor:pointer;position:relative;transition:transform .12s,background .12s;border:1px solid transparent}
    .dashboardMetric.live086:active{transform:scale(.98);background:#eef4ff}.dashboardMetric.live086:focus{outline:2px solid #2563eb;outline-offset:2px}
    .dashboardMetric.live086::after{content:'›';position:absolute;right:8px;top:50%;transform:translateY(-50%);font-size:18px;font-weight:900;color:#8592a8}.dashboardMetric.live086 span{padding-right:10px}
    .live086Hint{font-size:10px;color:#667085;margin-top:9px;line-height:1.4}
    #${PAGE} .live086Head{border:1px solid #d9e4f2;background:linear-gradient(145deg,#f8fbff,#fff)}.live086Back{background:transparent;color:#2563eb;padding:2px 0 9px;font-size:14px;font-weight:850}
    .live086Title{font-size:24px;font-weight:900;margin:0}.live086Meta{font-size:12px;color:#667085;line-height:1.45;margin-top:5px}.live086Section{margin-top:12px}.live086Section h3{margin:0 0 7px;font-size:16px}
    .live086Row{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;text-align:left;background:#fff;border:0;border-top:1px solid #e7ebf1;border-radius:0;padding:12px 2px;color:#182033}
    .live086Row:first-of-type{border-top:0}.live086Row:active{background:#f4f7fb}.live086Name{font-size:17px;font-weight:900;line-height:1.2}.live086Sub{font-size:11px;color:#6f7785;line-height:1.45;margin-top:4px}
    .live086Qty{text-align:right;font-size:18px;font-weight:900;white-space:nowrap}.live086Qty.low{color:#b42335}.live086Chevron{font-size:18px;color:#8490a3;margin-left:4px}.live086Empty{color:#6f7785;text-align:center;padding:22px 4px}
    @media(max-width:560px){.live086Title{font-size:21px}.live086Qty{font-size:16px}}
  `;document.head.appendChild(s)}
  function go(id){try{window.showPage(id)}catch{}setTimeout(()=>window.scrollTo({top:0,behavior:'auto'}),20)}
  function ensureLowStockPage(){let page=document.getElementById(PAGE);if(page)return page;const main=document.querySelector('main');if(!main)return null;page=document.createElement('section');page.id=PAGE;page.className='page hidden';page.innerHTML=`<div class="card live086Head"><button type="button" class="live086Back">‹ Back to Home</button><h2 class="live086Title">Low Stock</h2><div class="live086Meta">Live list using the same thresholds as the Home dashboard: general inventory ≤30 and active carpet rolls ≤50'. Tap any row to open the exact product or roll.</div></div><div id="live086LowBody"></div>`;main.appendChild(page);page.querySelector('.live086Back')?.addEventListener('click',()=>go('home'));return page}
  function generalLowStock(){const masters=window.loadMasters(),byId=new Map(masters.map(m=>[String(m.id),m]));let rows=window.loadInventoryRecords();if(typeof window.isCurrentGeneralInventoryRecord==='function')rows=rows.filter(window.isCurrentGeneralInventoryRecord);return rows.filter(r=>!r?.quantityPending&&Number(r?.quantity||0)<=30).map(r=>({r,m:byId.get(String(r.masterId))||{}})).sort((a,b)=>Number(a.r.quantity||0)-Number(b.r.quantity||0)||String(a.m.name||'').localeCompare(String(b.m.name||'')))}
  function carpetLowStock(){let rows=window.carpetRecords();if(typeof window.isCarpetWarehouseActive==='function')rows=rows.filter(window.isCarpetWarehouseActive);return rows.filter(r=>Number(r?.length)>0&&Number(r?.length)<=50).sort((a,b)=>Number(a.length||0)-Number(b.length||0)||String(a.roll||'').localeCompare(String(b.roll||''),undefined,{numeric:true}))}
  function feet(v){const inches=Math.round(Number(v||0)*12),f=Math.floor(inches/12),i=inches%12;return `${f}'${i?i+'"':''}`}
  function renderLowStock(){ensureStyle();const page=ensureLowStockPage();if(!page)return;const body=page.querySelector('#live086LowBody'),general=generalLowStock(),carpet=carpetLowStock();const generalHtml=general.length?general.map(({r,m})=>`<button class="live086Row" data-kind="inventory" data-master="${esc(r.masterId)}"><div><div class="live086Name">${esc(m.name||'Unknown Product')}${m.color?' · '+esc(m.color):''}</div><div class="live086Sub">${esc(r.location||'No location')}${r.lotNumber?' · Lot '+esc(r.lotNumber):''}${r.poNumber?' · PO '+esc(r.poNumber):''} · ${esc(m.category||'Other')}</div></div><div class="live086Qty low">${esc(Number(r.quantity||0))} ${esc(r.unit||'')} <span class="live086Chevron">›</span></div></button>`).join(''):'<div class="live086Empty">No low-stock general inventory.</div>';const carpetHtml=carpet.length?carpet.map(r=>`<button class="live086Row" data-kind="carpet" data-id="${esc(r.id)}"><div><div class="live086Name">${esc(r.collection||r.product||'Carpet')} · ${esc(r.colour||r.color||'')}</div><div class="live086Sub">Roll ${esc(r.roll||'—')} · ${esc(r.location||'No location')} · ${esc(r.status||r.measure||'Active')}</div></div><div class="live086Qty low">${esc(feet(r.length))} <span class="live086Chevron">›</span></div></button>`).join(''):'<div class="live086Empty">No carpet rolls at or below 50'.</div>';body.innerHTML=`<div class="card live086Section"><h3>📦 General Inventory · ${general.length}</h3>${generalHtml}</div><div class="card live086Section"><h3>🧶 Carpet · ${carpet.length}</h3>${carpetHtml}</div>`;body.querySelectorAll('[data-kind="inventory"]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.master;if(typeof window.openInventoryManager==='function')window.openInventoryManager(id);else go('inventory')}));body.querySelectorAll('[data-kind="carpet"]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.id;if(typeof window.openCarpetDetail==='function')window.openCarpetDetail(id);else go('carpetInventory')}))}
  function openLowStock(){renderLowStock();go(PAGE)}
  function makeLive(metricId,action,label){const value=document.getElementById(metricId),card=value?.closest('.dashboardMetric');if(!card||card.dataset.live086)return;card.dataset.live086='1';card.classList.add('live086');card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',label);card.addEventListener('click',action);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action()}})}
  function install(){if(!ready())return;ensureStyle();ensureLowStockPage();makeLive('dashProducts',()=>go('products'),'Open Products');makeLive('dashUnits',()=>go('inventory'),'Open Inventory');makeLive('dashLocations',()=>go('warehouseMap'),'Open Warehouse Map');makeLive('dashLowStock',openLowStock,'Open Low Stock details');const stats=document.querySelector('#home .dashboardStats');if(stats&&!stats.parentElement.querySelector('.live086Hint')){const h=document.createElement('div');h.className='live086Hint';h.textContent='Live Links pilot · tap any Inventory Summary number to open the underlying view.';stats.insertAdjacentElement('afterend',h)}installed=true}
  window.openRunluLowStock=openLowStock;
  function boot(){install();let n=0;const t=setInterval(()=>{install();if(installed&&++n>80)clearInterval(t)},250);window.addEventListener('pageshow',()=>setTimeout(install,80));window.addEventListener('storage',()=>{if(!document.getElementById(PAGE)?.classList.contains('hidden'))setTimeout(renderLowStock,100)})}
  if(document.readyState==='complete')boot();else window.addEventListener('load',boot,{once:true});
})();