/* RUNLU Warehouse OS — encrypted customer-owned local backup / restore. */
(function(global){
'use strict';
const FORMAT='RUNLU-WAREHOUSE-BACKUP';
const VERSION=1;
const ITERATIONS=220000;
const enc=new TextEncoder(),dec=new TextDecoder();
function hex(bytes){return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
function unhex(s){const out=new Uint8Array(s.length/2);for(let i=0;i<out.length;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
function requirePassphrase(v){const s=String(v||'');if(s.length<6)throw new Error('Backup password must be at least 6 characters.');return s}
async function derive(pass,salt,usage){const material=await crypto.subtle.importKey('raw',enc.encode(requirePassphrase(pass)),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,[usage])}
function tenantPrefix(ws){return `runlu-universal-v1::${ws.organizationId}::${ws.warehouseId}::`}
function capture(){const W=global.RUNLUWorkspace;if(!W?.isReady?.())throw new Error('No warehouse workspace is configured.');if(!W.can('backupData'))throw new Error('Owner role required to create a full backup.');const ws=W.workspace(),prefix=tenantPrefix(ws),tenantStorage={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith(prefix))tenantStorage[k]=localStorage.getItem(k)}return{format:FORMAT,schemaVersion:VERSION,createdAt:new Date().toISOString(),workspace:ws,tenantStorage}}
async function exportEncrypted(passphrase){if(!crypto?.subtle)throw new Error('Secure backup encryption is unavailable on this device.');const payload=capture(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(passphrase,salt,'encrypt'),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload)));return JSON.stringify({format:FORMAT,version:VERSION,encrypted:true,cipher:'AES-GCM-256',kdf:'PBKDF2-SHA256',iterations:ITERATIONS,createdAt:payload.createdAt,salt:hex(salt),iv:hex(iv),ciphertext:hex(new Uint8Array(cipher))})}
function validatePayload(payload){if(!payload||payload.format!==FORMAT||payload.schemaVersion!==VERSION)throw new Error('This is not a supported RUNLU Warehouse OS backup.');const ws=payload.workspace;if(!ws?.organizationId||!ws?.warehouseId||!ws?.config?.company||!ws?.config?.warehouse)throw new Error('Backup workspace information is incomplete.');const prefix=tenantPrefix(ws),data=payload.tenantStorage;if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('Backup data section is invalid.');for(const k of Object.keys(data))if(!k.startsWith(prefix))throw new Error('Backup contains a storage key outside its warehouse namespace.');return payload}
async function decryptEnvelope(text,passphrase){if(!crypto?.subtle)throw new Error('Secure backup decryption is unavailable on this device.');let env;try{env=JSON.parse(String(text||''))}catch(_){throw new Error('Backup file is not valid JSON.')}if(env?.format!==FORMAT||env?.version!==VERSION||env?.encrypted!==true)throw new Error('This is not a supported encrypted RUNLU Warehouse OS backup.');try{const salt=unhex(env.salt),iv=unhex(env.iv),cipher=unhex(env.ciphertext),key=await derive(passphrase,salt,'decrypt'),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher);return validatePayload(JSON.parse(dec.decode(plain)))}catch(err){if(String(err?.message||'').includes('supported'))throw err;throw new Error('Backup password is incorrect or the backup file is damaged.') }}
function clearUniversalStorage(){const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('runlu-universal-v1::'))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k))}
async function restoreEncrypted(text,passphrase){const payload=await decryptEnvelope(text,passphrase);clearUniversalStorage();localStorage.setItem(global.RUNLUWorkspace.WORKSPACE_KEY,JSON.stringify(payload.workspace));for(const [k,v] of Object.entries(payload.tenantStorage))localStorage.setItem(k,String(v));localStorage.removeItem(global.RUNLUWorkspace.SESSION_KEY);return payload.workspace}
function fileName(){const ws=global.RUNLUWorkspace?.workspace?.(),company=String(ws?.config?.company?.name||'warehouse').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'warehouse',date=new Date().toISOString().slice(0,10);return `runlu-${company}-${date}.warehouse-backup.json`}
global.RUNLUBackup=Object.freeze({FORMAT,VERSION,ITERATIONS,capture,exportEncrypted,decryptEnvelope,restoreEncrypted,fileName});
})(typeof window!=='undefined'?window:globalThis);
