-- RUNLU Warehouse OS — Universal V1 multi-tenant foundation
-- DEVELOPMENT ONLY. Do not run against the production database without review.
-- Isolated under /universal on product/universal-v1.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  logo_url text,
  website_url text,
  support_email text,
  default_currency text not null default 'USD',
  default_locale text not null default 'en',
  timezone text not null default 'UTC',
  plan_code text not null default 'trial',
  trial_ends_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','manager','member','viewer')),
  status text not null default 'active' check (status in ('invited','active','suspended')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.warehouses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  code text not null,
  address jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, code)
);

-- Compatibility layer for the mature dataset-oriented app.
-- warehouse_id may be null for organization-wide datasets. A generated scope_id
-- makes nullable warehouse scope safely unique without incorrectly forcing warehouse_id NOT NULL.
create table if not exists public.tenant_datasets (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  warehouse_id uuid references public.warehouses(id) on delete cascade,
  scope_id uuid generated always as (
    coalesce(warehouse_id, '00000000-0000-0000-0000-000000000000'::uuid)
  ) stored,
  dataset_key text not null,
  payload jsonb not null default '[]'::jsonb,
  device_id text,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  unique (organization_id, scope_id, dataset_key)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  warehouse_id uuid references public.warehouses(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  entity_type text,
  entity_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists organization_members_user_idx on public.organization_members(user_id, status);
create index if not exists warehouses_org_idx on public.warehouses(organization_id, is_active);
create index if not exists tenant_datasets_org_wh_idx on public.tenant_datasets(organization_id, warehouse_id, updated_at desc);
create index if not exists audit_events_org_created_idx on public.audit_events(organization_id, created_at desc);

create or replace function public.runlu_set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists organizations_updated_at on public.organizations;
create trigger organizations_updated_at before update on public.organizations
for each row execute function public.runlu_set_updated_at();

drop trigger if exists warehouses_updated_at on public.warehouses;
create trigger warehouses_updated_at before update on public.warehouses
for each row execute function public.runlu_set_updated_at();

drop trigger if exists tenant_datasets_updated_at on public.tenant_datasets;
create trigger tenant_datasets_updated_at before update on public.tenant_datasets
for each row execute function public.runlu_set_updated_at();

-- SECURITY DEFINER helpers avoid recursive RLS checks on organization_members.
create or replace function public.runlu_is_org_member(target_org uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = target_org and m.user_id = auth.uid() and m.status = 'active'
  );
$$;

create or replace function public.runlu_has_org_role(target_org uuid, allowed_roles text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = target_org and m.user_id = auth.uid()
      and m.status = 'active' and m.role = any(allowed_roles)
  );
$$;

-- Atomic self-service onboarding. Creates organization + owner membership + first warehouse
-- in one transaction so there is never a tenant with no owner.
create or replace function public.runlu_create_organization(
  p_name text,
  p_slug text,
  p_warehouse_name text default 'Main Warehouse',
  p_warehouse_code text default 'MAIN',
  p_website_url text default null,
  p_support_email text default null,
  p_currency text default 'USD',
  p_locale text default 'en',
  p_timezone text default 'UTC',
  p_warehouse_settings jsonb default '{}'::jsonb
)
returns table (organization_id uuid, warehouse_id uuid)
language plpgsql security definer set search_path = '' as $$
declare
  v_user uuid := auth.uid();
  v_org uuid;
  v_warehouse uuid;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if nullif(trim(p_name),'') is null then raise exception 'Organization name is required'; end if;
  if nullif(trim(p_slug),'') is null then raise exception 'Organization slug is required'; end if;
  if nullif(trim(p_warehouse_name),'') is null then raise exception 'Warehouse name is required'; end if;
  if nullif(trim(p_warehouse_code),'') is null then raise exception 'Warehouse code is required'; end if;

  insert into public.organizations (
    name, slug, website_url, support_email, default_currency, default_locale,
    timezone, plan_code, trial_ends_at, created_by
  ) values (
    trim(p_name), lower(trim(p_slug)), nullif(trim(p_website_url),''), nullif(trim(p_support_email),''),
    upper(trim(coalesce(p_currency,'USD'))), lower(trim(coalesce(p_locale,'en'))),
    trim(coalesce(p_timezone,'UTC')), 'trial', now() + interval '14 days', v_user
  ) returning id into v_org;

  insert into public.organization_members (organization_id, user_id, role, status)
  values (v_org, v_user, 'owner', 'active');

  insert into public.warehouses (organization_id, name, code, settings)
  values (v_org, trim(p_warehouse_name), upper(trim(p_warehouse_code)), coalesce(p_warehouse_settings,'{}'::jsonb))
  returning id into v_warehouse;

  insert into public.audit_events (organization_id, warehouse_id, actor_user_id, event_type, entity_type, entity_id, payload)
  values (v_org, v_warehouse, v_user, 'workspace.created', 'organization', v_org::text,
    jsonb_build_object('warehouse_id',v_warehouse,'plan_code','trial'));

  return query select v_org, v_warehouse;
end;
$$;

revoke all on function public.runlu_is_org_member(uuid) from public;
revoke all on function public.runlu_has_org_role(uuid, text[]) from public;
revoke all on function public.runlu_create_organization(text,text,text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.runlu_is_org_member(uuid) to authenticated;
grant execute on function public.runlu_has_org_role(uuid, text[]) to authenticated;
grant execute on function public.runlu_create_organization(text,text,text,text,text,text,text,text,text,jsonb) to authenticated;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.warehouses enable row level security;
alter table public.tenant_datasets enable row level security;
alter table public.audit_events enable row level security;

create policy "members can read organizations" on public.organizations for select to authenticated
using (public.runlu_is_org_member(id));
create policy "authenticated users can create organizations" on public.organizations for insert to authenticated
with check (created_by = auth.uid());
create policy "owners admins can update organizations" on public.organizations for update to authenticated
using (public.runlu_has_org_role(id,array['owner','admin']))
with check (public.runlu_has_org_role(id,array['owner','admin']));

create policy "members can read organization membership" on public.organization_members for select to authenticated
using (public.runlu_is_org_member(organization_id));
create policy "owners admins can add members" on public.organization_members for insert to authenticated
with check (public.runlu_has_org_role(organization_id,array['owner','admin']));
create policy "owners admins can update members" on public.organization_members for update to authenticated
using (public.runlu_has_org_role(organization_id,array['owner','admin']))
with check (public.runlu_has_org_role(organization_id,array['owner','admin']));
create policy "owners admins can remove members" on public.organization_members for delete to authenticated
using (public.runlu_has_org_role(organization_id,array['owner','admin']));

create policy "members can read warehouses" on public.warehouses for select to authenticated
using (public.runlu_is_org_member(organization_id));
create policy "managers can create warehouses" on public.warehouses for insert to authenticated
with check (public.runlu_has_org_role(organization_id,array['owner','admin','manager']));
create policy "managers can update warehouses" on public.warehouses for update to authenticated
using (public.runlu_has_org_role(organization_id,array['owner','admin','manager']))
with check (public.runlu_has_org_role(organization_id,array['owner','admin','manager']));

create policy "members can read tenant datasets" on public.tenant_datasets for select to authenticated
using (public.runlu_is_org_member(organization_id));
create policy "members can create tenant datasets" on public.tenant_datasets for insert to authenticated
with check (public.runlu_is_org_member(organization_id) and updated_by = auth.uid());
create policy "members can update tenant datasets" on public.tenant_datasets for update to authenticated
using (public.runlu_is_org_member(organization_id))
with check (public.runlu_is_org_member(organization_id) and updated_by = auth.uid());
create policy "managers can delete tenant datasets" on public.tenant_datasets for delete to authenticated
using (public.runlu_has_org_role(organization_id,array['owner','admin','manager']));

create policy "members can read audit events" on public.audit_events for select to authenticated
using (public.runlu_is_org_member(organization_id));
create policy "members can append audit events" on public.audit_events for insert to authenticated
with check (public.runlu_is_org_member(organization_id) and actor_user_id = auth.uid());

grant select, insert, update, delete on public.organizations to authenticated;
grant select, insert, update, delete on public.organization_members to authenticated;
grant select, insert, update, delete on public.warehouses to authenticated;
grant select, insert, update, delete on public.tenant_datasets to authenticated;
grant select, insert on public.audit_events to authenticated;
