#!/usr/bin/env python3
"""
Warehouse OS V7 disposable dry-run loader.

Consumes a manifest generated by snapshot-manifest-cli.mjs and loads ONLY a disposable
Postgres database named warehouse_v7_test. It stages every record, applies the formal
classification API, imports only VALID records through V7 import functions, then emits
a reconciliation report.

This script intentionally refuses to run against any other database name.
"""
import argparse, json, os, subprocess, sys, uuid
from decimal import Decimal

DB = os.environ.get("PGDATABASE", "warehouse_v7_test")
CONN = f"host={os.environ.get('PGHOST','localhost')} port={os.environ.get('PGPORT','5432')} dbname={DB} user={os.environ.get('PGUSER','postgres')} password={os.environ.get('PGPASSWORD','postgres')}"
ENV = os.environ.copy()
ENV.setdefault("PGPASSWORD", os.environ.get("PGPASSWORD", "postgres"))

def run(sql, ok=True):
    r = subprocess.run(["psql", CONN, "-v", "ON_ERROR_STOP=1", "-Atc", sql], text=True, capture_output=True, env=ENV)
    if ok and r.returncode != 0:
        raise RuntimeError(r.stderr.strip() or r.stdout.strip())
    return r

def value(r):
    lines=[x.strip() for x in r.stdout.splitlines() if x.strip() and x.strip()!="SET"]
    return lines[-1] if lines else ""

def q(s):
    return "'" + str(s).replace("'","''") + "'"

def j(v):
    return q(json.dumps(v,separators=(",",":"),ensure_ascii=False)) + "::jsonb"

def ensure_disposable_db():
    name=value(run("select current_database();"))
    if name != "warehouse_v7_test":
        raise RuntimeError(f"DRY_RUN_REFUSES_DATABASE:{name}")

def ensure_admin(tenant, actor):
    run(f"insert into warehouse_v7.tenant_member(tenant_id,user_id,role,lifecycle) values({q(tenant)}::uuid,{q(actor)}::uuid,'admin','active') on conflict(tenant_id,user_id) do update set role='admin',lifecycle='active';")

def stage_legacy(tenant, item):
    source=item.get("source_payload") or {}
    normalized=item.get("transformed") or {}
    r=run(f"select warehouse_v7.stage_legacy_record({q(tenant)}::uuid,{q(item['dataset'])},{q(item['record_id'])},{j(source)},{j(normalized)});")
    return value(r)

def stage_derived_carpet_product(tenant, item):
    evidence=item.get("evidence") or []
    source=(item.get("transformed") or {}).get("source_code") or item["record_id"].replace("CARPET_SOURCE:","",1)
    sid=None
    if evidence:
        for e in evidence:
            r=run(f"select warehouse_v7.stage_derived_carpet_product({q(tenant)}::uuid,{q(source)},{q(e.get('name') or '')},{q(e.get('colour') or '')});")
            sid=value(r)
    else:
        t=item.get("transformed") or {}
        r=run(f"select warehouse_v7.stage_derived_carpet_product({q(tenant)}::uuid,{q(source)},{q(t.get('name') or '')},{q(t.get('colour') or '')});")
        sid=value(r)
    return sid

def get_stage_state(tenant, sid):
    r=run(f"select classification||'|'||coalesce(imported_entity_type,'')||'|'||coalesce(imported_entity_id::text,'') from warehouse_v7.migration_staging where tenant_id={q(tenant)}::uuid and id={q(sid)}::uuid;")
    parts=value(r).split("|")
    return {"classification":parts[0],"imported_entity_type":parts[1] if len(parts)>1 else "","imported_entity_id":parts[2] if len(parts)>2 else ""}

def classify(tenant, sid, cls, reason, actor):
    state=get_stage_state(tenant,sid)
    if state["classification"]=="imported":
        if cls!="valid":
            raise RuntimeError(f"MANIFEST_CHANGED_AFTER_IMPORT:{sid}:{cls}")
        return
    if state["classification"]==cls:
        return
    run(f"set request.jwt.claim.sub={q(actor)}; select warehouse_v7.classify_legacy_record({q(tenant)}::uuid,{q(sid)}::uuid,{q(cls)},{q(reason or '')},{q(actor)}::uuid);")

def import_valid(tenant, sid, item, actor):
    dataset=item["dataset"]
    fn=None
    if dataset in ("runlu_product_master_v21","derived_carpet_product_v6"):
        fn="import_valid_product"
    elif dataset=="derived_location_v6":
        fn="import_valid_location"
    elif dataset in ("runlu_inventory_records_v21","derived_inventory_item_v6"):
        fn="import_valid_stock_item"
    elif dataset in ("runlu_carpet_inventory_v52","derived_carpet_roll_v6"):
        fn="import_valid_carpet_roll"
    else:
        raise RuntimeError(f"NO_IMPORT_FUNCTION:{dataset}")
    r=run(f"set request.jwt.claim.sub={q(actor)}; select warehouse_v7.{fn}({q(tenant)}::uuid,{q(sid)}::uuid,{q(actor)}::uuid);")
    return value(r)

def process_group(tenant, actor, items, derived=False):
    result={"staged":0,"imported":0}
    for item in items:
        sid=stage_derived_carpet_product(tenant,item) if derived else stage_legacy(tenant,item)
        result["staged"]+=1
        classify(tenant,sid,item["classification"],item.get("reason",""),actor)
        if item["classification"]=="valid":
            import_valid(tenant,sid,item,actor)
            result["imported"]+=1
    return result

def sql_json(sql):
    r=run("select row_to_json(x)::text from ("+sql+") x;")
    return json.loads(value(r))

def decimal_text(v):
    d=Decimal(str(v))
    return format(d.normalize(),"f") if d else "0"

def reconcile(tenant, manifest):
    valid_stock=[x for k in ("inventory","derived_inventory_items") for x in manifest.get(k,[]) if x["classification"]=="valid"]
    valid_carpet=[x for k in ("carpet","derived_carpet_rolls") for x in manifest.get(k,[]) if x["classification"]=="valid"]

    stock_totals={}
    for x in valid_stock:
        t=x.get("transformed") or {}
        u=str(t.get("unit") or "")
        stock_totals[u]=stock_totals.get(u,Decimal("0"))+Decimal(str(t.get("quantity") or 0))
    expected_stock_by_unit={k:decimal_text(v) for k,v in sorted(stock_totals.items())}

    expected_carpet_remaining=sum(int((x.get("transformed") or {}).get("remaining_sixteenths") or 0) for x in valid_carpet)

    expected={
      "products":sum(1 for x in manifest["products"] if x["classification"]=="valid")+sum(1 for x in manifest["derived_carpet_products"] if x["classification"]=="valid"),
      "locations":sum(1 for x in manifest["locations"] if x["classification"]=="valid"),
      "stock_items":len(valid_stock),
      "carpet_rolls":len(valid_carpet)
    }
    actual=sql_json(f"""
      select
        (select count(*) from warehouse_v7.product where tenant_id={q(tenant)}::uuid) products,
        (select count(*) from warehouse_v7.location where tenant_id={q(tenant)}::uuid) locations,
        (select count(*) from warehouse_v7.stock_item where tenant_id={q(tenant)}::uuid) stock_items,
        (select count(*) from warehouse_v7.carpet_roll where tenant_id={q(tenant)}::uuid) carpet_rolls,
        (select count(*) from warehouse_v7.command where tenant_id={q(tenant)}::uuid and status='committed') committed_commands,
        (select count(*) from warehouse_v7.inventory_movement where tenant_id={q(tenant)}::uuid) movements,
        (select count(*) from warehouse_v7.event where tenant_id={q(tenant)}::uuid) events,
        (select count(*) from warehouse_v7.migration_staging where tenant_id={q(tenant)}::uuid and classification='imported') imported_staging,
        (select count(*) from warehouse_v7.migration_staging where tenant_id={q(tenant)}::uuid and classification<>'imported' and imported_entity_id is not null) invalid_with_canonical_link,
        (select coalesce(jsonb_object_agg(unit,total),'{{}}'::jsonb) from
          (select unit,sum(quantity)::text total from warehouse_v7.stock_item where tenant_id={q(tenant)}::uuid group by unit) q) stock_quantity_by_unit,
        (select coalesce(jsonb_object_agg(unit,total),'{{}}'::jsonb) from
          (select unit,sum(quantity)::text total from warehouse_v7.inventory_movement where tenant_id={q(tenant)}::uuid and movement_type='OPENING_IMPORT' group by unit) q) opening_stock_movement_by_unit,
        (select coalesce(sum(remaining_sixteenths),0) from warehouse_v7.carpet_roll where tenant_id={q(tenant)}::uuid) carpet_remaining_sixteenths,
        (select coalesce(sum(quantity),0) from warehouse_v7.inventory_movement where tenant_id={q(tenant)}::uuid and movement_type='OPENING_ROLL_IMPORT') opening_carpet_movement_sixteenths
    """)
    expected_opening=expected["stock_items"]+expected["carpet_rolls"]
    actual_stock_by_unit={k:decimal_text(v) for k,v in sorted((actual.get("stock_quantity_by_unit") or {}).items())}
    actual_stock_movements={k:decimal_text(v) for k,v in sorted((actual.get("opening_stock_movement_by_unit") or {}).items())}
    checks={
      "canonical_counts_match":all(actual[k]==expected[k] for k in ("products","locations","stock_items","carpet_rolls")),
      "opening_commands_match":actual["committed_commands"]==expected_opening,
      "opening_movements_match":actual["movements"]==expected_opening,
      "opening_events_match":actual["events"]==expected_opening,
      "invalid_rows_have_no_canonical_link":actual["invalid_with_canonical_link"]==0,
      "stock_quantity_by_unit_match":actual_stock_by_unit==expected_stock_by_unit,
      "opening_stock_movement_quantity_match":actual_stock_movements==expected_stock_by_unit,
      "carpet_remaining_measure_match":int(actual["carpet_remaining_sixteenths"])==expected_carpet_remaining,
      "opening_carpet_movement_measure_match":int(Decimal(str(actual["opening_carpet_movement_sixteenths"])))==expected_carpet_remaining
    }
    return {
      "expected":expected,
      "expected_opening_ledger_rows":expected_opening,
      "expected_stock_quantity_by_unit":expected_stock_by_unit,
      "expected_carpet_remaining_sixteenths":expected_carpet_remaining,
      "actual":actual,
      "checks":checks,
      "pass":all(checks.values())
    }

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("manifest")
    ap.add_argument("--report",default="/tmp/v7-dry-run-report.json")
    ap.add_argument("--tenant")
    ap.add_argument("--actor")
    ap.add_argument("--expected-source-md5")
    args=ap.parse_args()
    ensure_disposable_db()
    tenant=args.tenant or str(uuid.uuid4())
    actor=args.actor or str(uuid.uuid4())
    with open(args.manifest,encoding="utf-8") as fh:
        manifest=json.load(fh)
    source_integrity=manifest.get("source_integrity") or {}
    if args.expected_source_md5:
        actual_md5=source_integrity.get("snapshot_md5")
        if actual_md5!=args.expected_source_md5:
            raise RuntimeError(f"SNAPSHOT_FINGERPRINT_MISMATCH:expected={args.expected_source_md5}:actual={actual_md5}")
        if not source_integrity.get("postgres_jsonb_text_verified"):
            raise RuntimeError("SNAPSHOT_FINGERPRINT_NOT_POSTGRES_VERIFIED")
    ensure_admin(tenant,actor)

    processed={}
    processed["products"]=process_group(tenant,actor,manifest["products"])
    processed["derived_carpet_products"]=process_group(tenant,actor,manifest["derived_carpet_products"],derived=True)
    processed["locations"]=process_group(tenant,actor,manifest["locations"])
    processed["inventory"]=process_group(tenant,actor,manifest["inventory"])
    processed["derived_inventory_items"]=process_group(tenant,actor,manifest.get("derived_inventory_items",[]))
    processed["carpet"]=process_group(tenant,actor,manifest["carpet"])
    processed["derived_carpet_rolls"]=process_group(tenant,actor,manifest.get("derived_carpet_rolls",[]))

    report={
      "mode":"DISPOSABLE_POSTGRES_DRY_RUN",
      "production_writes":0,
      "tenant":tenant,
      "source_integrity":source_integrity,
      "manifest_summary":manifest["summary"],
      "processed":processed,
      "reconciliation":reconcile(tenant,manifest)
    }
    with open(args.report,"w",encoding="utf-8") as fh:
        json.dump(report,fh,indent=2,ensure_ascii=False)
        fh.write("\n")
    print(json.dumps(report,indent=2,ensure_ascii=False))
    if not report["reconciliation"]["pass"]:
        raise SystemExit(1)

if __name__=="__main__":
    main()
